# Generated by Django 5.2.10 on 2026-04-30 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Taklif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(max_length=200)),
                ('kategoriya', models.CharField(choices=[('infratuzilma', 'Infratuzilma'), ('xavfsizlik', 'Xavfsizlik'), ('ekologiya', 'Ekologiya'), ('ijtimoiy', 'Ijtimoiy'), ('madaniy', 'Madaniy'), ('boshqa', 'Boshqa')], default='boshqa', max_length=30)),
                ('ustuvorlik', models.CharField(choices=[('past', 'Past'), ('orta', "O'rta"), ('yuqori', 'Yuqori'), ('shoshilinch', 'Shoshilinch')], default='orta', max_length=20)),
                ('mazmun', models.TextField()),
                ('ko_rib_chiqildi', models.BooleanField(default=False)),
                ('yaratilgan', models.DateTimeField(auto_now_add=True)),
                ('muallif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='takliflar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-yaratilgan'],
            },
        ),
    ]
