# Generated by Django 5.2.10 on 2026-05-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MahallaInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuman', models.CharField(max_length=100)),
                ('mahalla', models.CharField(max_length=100)),
                ('manzil', models.CharField(blank=True, max_length=200)),
                ('telefon', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': "Mahalla ma'lumoti",
            },
        ),
        migrations.CreateModel(
            name='MahallaRahbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismi', models.CharField(max_length=150)),
                ('lavozim', models.CharField(choices=[('rais', 'Mahalla raisi'), ('hokim_yordamchisi', 'Hokim yordamchisi'), ('yoshlar', 'Yoshlar yetakchisi'), ('xotin_qizlar', 'Xotin-qizlar'), ('profilaktika', 'Profilaktika inspektori'), ('boshqa', 'Boshqa')], max_length=30)),
                ('lavozim_tavsifi', models.CharField(blank=True, max_length=200)),
                ('telefon', models.CharField(blank=True, max_length=20)),
                ('tartib', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['tartib'],
            },
        ),
    ]
