# Generated by Django 5.2.10 on 2026-05-10 14:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_mahallarahbar_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='RahbarXabar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yuboruvchi_ism', models.CharField(max_length=150)),
                ('yuboruvchi_telefon', models.CharField(blank=True, max_length=20)),
                ('matn', models.TextField()),
                ('yuborilgan_vaqt', models.DateTimeField(default=django.utils.timezone.now)),
                ('o_qilgan', models.BooleanField(default=False)),
                ('rahbar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xabarlar', to='pages.mahallarahbar')),
            ],
            options={
                'verbose_name': 'Rahbarga xabar',
                'ordering': ['-yuborilgan_vaqt'],
            },
        ),
    ]
