# Generated by Django 5.2.10 on 2026-05-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_rahbarxabar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rahbarxabar',
            name='o_qilgan',
        ),
        migrations.AddField(
            model_name='rahbarxabar',
            name='holat',
            field=models.CharField(choices=[('kutilmoqda', 'Kutilmoqda'), ('tasdiqlangan', 'Tasdiqlangan'), ('bekor_qilingan', 'Bekor qilingan')], default='kutilmoqda', max_length=20),
        ),
        migrations.AddField(
            model_name='rahbarxabar',
            name='javob',
            field=models.TextField(blank=True),
        ),
    ]
