# Generated by Django 5.2.10 on 2026-04-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(max_length=200)),
                ('mazmun', models.TextField()),
                ('sana', models.DateField()),
                ('faol', models.BooleanField(default=True)),
                ('yaratilgan', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-sana'],
            },
        ),
        migrations.CreateModel(
            name='IshOrni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(max_length=200)),
                ('mazmun', models.TextField()),
                ('muddat', models.DateField()),
                ('faol', models.BooleanField(default=True)),
                ('yaratilgan', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-yaratilgan'],
            },
        ),
    ]
