# Generated by Django 5.2.10 on 2026-04-30 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Murojaat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('mavzu', models.CharField(max_length=200)),
                ('kategoriya', models.CharField(choices=[('kommunal', 'Kommunal xizmatlar'), ('yol', "Yo'l va ko'cha"), ('xavfsizlik', 'Xavfsizlik'), ('sanitariya', 'Sanitariya va ekologiya'), ('ijtimoiy', 'Ijtimoiy yordam'), ('boshqa', 'Boshqa')], default='boshqa', max_length=30)),
                ('mas_ul', models.CharField(blank=True, max_length=150)),
                ('mazmun', models.TextField()),
                ('holat', models.CharField(choices=[('yuborildi', 'Yuborildi'), ('jarayonda', 'Jarayonda'), ('bajarildi', 'Bajarildi'), ('rad_etildi', 'Rad etildi')], default='yuborildi', max_length=20)),
                ('javob', models.TextField(blank=True)),
                ('yaratilgan', models.DateTimeField(auto_now_add=True)),
                ('yangilangan', models.DateTimeField(auto_now=True)),
                ('muallif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='murojaatlar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-yaratilgan'],
            },
        ),
    ]
