# Generated by Django 5.2.10 on 2026-05-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('murojaatlar', '0002_murojaat_mas_ul_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='murojaat',
            name='fullname',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='murojaat',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
